# Generated by Django 3.1.1 on 2021-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribed_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('subscribe_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
