# Generated by Django 3.1.1 on 2021-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('booking_time', models.DateTimeField()),
                ('people', models.PositiveIntegerField(blank=True, null=True)),
                ('booked', models.BooleanField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
