# Generated by Django 3.1.1 on 2021-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0002_unverified_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverified_user',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
